language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - cd example
  - python -Wall manage.py test table

